In [1]:
from tensorflow import keras
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

# 1. 데이터 불러오기
(train_data,train_label),(test_data,test_label) = keras.datasets.fashion_mnist.load_data()

# print(train_data[0]) #0번째일 경우 구두의 형상
# print(train_label[0]) #[9 0 0 ... 3 0 5] #9

# [[[0 0 0 ... 0 0 0]
#   [0 0 0 ... 0 0 0]
# [0 0 0 ... 0 0 0]]]

# 모든 데이터는 숫자화 필요.



4431872/4422102 [==============================] - 0s 0us/step


In [2]:
# train_data.shape

In [3]:
# 2. 표준화 작업
train_data = train_data/255
test_data = test_data/255

In [4]:
# 3. 훈련데이터, 테스트데이터 분리

train_scaled,val_scaled,train_label,val_label = train_test_split(train_data,train_label)

In [5]:
# 4. 딥러닝 선언

model = keras.Sequential()
model.add(keras.layers.Flatten(input_shape=(28,28))) # 확인할것
model.add(keras.layers.Dense(100,activation='relu'))
model.add(keras.layers.Dense(10,activation='softmax'))
model.compile(loss='sparse_categorical_crossentropy', metrics='accuracy') # 원핫 인코딩 다중 분류




In [6]:
# 5. 딥러닝 훈련
model.fit(train_scaled,train_label,epochs=5)

Epoch 1/5
1407/1407 [==============================] - 4s 2ms/step - loss: 0.5461 - accuracy: 0.8101
Epoch 2/5
1407/1407 [==============================] - 6s 4ms/step - loss: 0.4009 - accuracy: 0.8580
Epoch 3/5
1407/1407 [==============================] - 6s 4ms/step - loss: 0.3587 - accuracy: 0.8711
Epoch 4/5
1407/1407 [==============================] - 3s 2ms/step - loss: 0.3397 - accuracy: 0.8795
Epoch 5/5
1407/1407 [==============================] - 4s 3ms/step - loss: 0.3235 - accuracy: 0.8861


In [7]:
# 6. 정확도
score = model.evaluate(val_scaled,val_label)
score

469/469 [==============================] - 1s 1ms/step - loss: 0.3420 - accuracy: 0.8791


[0.34202978014945984, 0.8791333436965942]